"""fix coal price model

Revision ID: 85b1644ed66f
Revises: 44bab3a17140
Create Date: 2024-08-08 13:07:19.152411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b1644ed66f'
down_revision: Union[str, None] = '44bab3a17140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_engine1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_T_COALPRICE_id', table_name='T_COALPRICE')
    op.drop_table('T_COALPRICE')
    op.drop_index('ix_T_MONTHLYSALES_id', table_name='T_MONTHLYSALES')
    op.drop_table('T_MONTHLYSALES')
    op.drop_index('ix_T_KOMTRAX_id', table_name='T_KOMTRAX')
    op.drop_table('T_KOMTRAX')
    # ### end Alembic commands ###


def downgrade_engine1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_KOMTRAX',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('model', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('smr', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('working_hour', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('actual_working_hour', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('longitude_location', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('latitude_location', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__T_KOMTRA__3213E83FB022574E')
    )
    op.create_index('ix_T_KOMTRAX_id', 'T_KOMTRAX', ['id'], unique=False)
    op.create_table('T_MONTHLYSALES',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('quantity_sold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_unit', sa.DECIMAL(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_sales', sa.DECIMAL(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('sales_region', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('salesperson', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__T_MONTHL__3213E83F8C32114C')
    )
    op.create_index('ix_T_MONTHLYSALES_id', 'T_MONTHLYSALES', ['id'], unique=False)
    op.create_table('T_COALPRICE',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__T_COALPR__3213E83F2A18ECB9')
    )
    op.create_index('ix_T_COALPRICE_id', 'T_COALPRICE', ['id'], unique=False)
    # ### end Alembic commands ###


def upgrade_engine2() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_T_MONTHLYSALESCLEAN_id', table_name='T_MONTHLYSALESCLEAN')
    op.drop_table('T_MONTHLYSALESCLEAN')
    op.drop_index('ix_T_COALPRICECLEAN_id', table_name='T_COALPRICECLEAN')
    op.drop_table('T_COALPRICECLEAN')
    op.drop_index('ix_T_KOMTRAXCLEAN_id', table_name='T_KOMTRAXCLEAN')
    op.drop_table('T_KOMTRAXCLEAN')
    # ### end Alembic commands ###


def downgrade_engine2() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_KOMTRAXCLEAN',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('model', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('smr', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('working_hour', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('actual_working_hour', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('longitude_location', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.Column('latitude_location', sa.DECIMAL(precision=10, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__T_KOMTRA__3213E83FC5048F72')
    )
    op.create_index('ix_T_KOMTRAXCLEAN_id', 'T_KOMTRAXCLEAN', ['id'], unique=False)
    op.create_table('T_COALPRICECLEAN',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__T_COALPR__3213E83F4572B16D')
    )
    op.create_index('ix_T_COALPRICECLEAN_id', 'T_COALPRICECLEAN', ['id'], unique=False)
    op.create_table('T_MONTHLYSALESCLEAN',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('quantity_sold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_unit', sa.DECIMAL(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_sales', sa.DECIMAL(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('sales_region', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('salesperson', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__T_MONTHL__3213E83FF4D7DD51')
    )
    op.create_index('ix_T_MONTHLYSALESCLEAN_id', 'T_MONTHLYSALESCLEAN', ['id'], unique=False)
    # ### end Alembic commands ###

